[package]
name = "kubectl-why-can"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
hyper = { version = "0.14.13", features = ["client", "http1", "stream", "tcp"] }
k8s-openapi = { version = "0.14.0", default-features = false, features=["v1_21"] }
kube = { version = "^0.71.0" }
kube-derive = { version = "^0.71.0" }
tokio = { version = "1.14.0", features = ["full"] }
tower = { version = "0.4.6", features = ["limit"] }
tower-http = { version = "0.2.0", features = ["trace", "decompression-gzip"] }
tracing-subscriber = "0.3.3"
