name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
      - name: Cache rust build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            target
          key: rust-build-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          use-cross: true
          args: --target ${{ matrix.target }}
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --target ${{ matrix.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: kubectl-why-can-${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/kubectl-why-can
          retention-days: 7
